# Development Docker Compose
version: '3.8'

services:
  portfolio-website-dev:
    build:
      context: ..
      dockerfile: src/Dockerfile.dev
    container_name: portfolio-website-dev
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=development
      - VITE_GA_ID=${VITE_GA_ID:-G-DEVELOPMENT}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY:-}
    stdin_open: true
    tty: true
    networks:
      - portfolio-dev-network
    restart: unless-stopped

networks:
  portfolio-dev-network:
    driver: bridge
