# Development Docker Compose
version: '3.8'

services:
  portfolio-website-dev:
    build:
      context: ..
      dockerfile: src/Dockerfile.dev
    container_name: portfolio-website-dev
    ports:
      - "3000:5173"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    networks:
      - portfolio-dev-network
    restart: unless-stopped

networks:
  portfolio-dev-network:
    driver: bridge